server :
  port: 8080
  servlet:
    context-path: /


spring :
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/noticeboard?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  mvc :
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools :
    livereload:
      enabled: true
    restart:
      enabled: false

mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations:
    - classpath:mybatis/mapper/*.xml